"""Added description to Project model

Revision ID: 4dc5f7e49ca8
Revises: 
Create Date: 2020-01-27 05:41:29.983495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc5f7e49ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'project', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'description')
    # ### end Alembic commands ###
